name: Update README ⭐
on:
  workflow_dispatch:
#  schedule:
#    - cron: "55 */4 * * *"  # Every 4 hours on the 55th minute

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 362122
          leaderboardId: 362122
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2024
      - uses: stefanzweifel/git-auto-commit-action@v5 # use v5
        with:
          commit_message: Update README stars